# Generated by Django 4.1.6 on 2023-02-26 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя товара')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание товара')),
                ('image', models.CharField(max_length=300, verbose_name='Фото товара')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('grocery', 'Бакалея'), ('drinks', 'Напитки'), ('household chemicals', 'Бытовая химия')], default='other', max_length=200, verbose_name='Категория')),
                ('product_left', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
            ],
        ),
    ]
