# Generated by Django 4.1.6 on 2023-03-14 07:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_product_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_in_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='webapp.product')),
            ],
        ),
    ]
