# Generated by Django 4.1.6 on 2023-03-14 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_product_in_cart_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
                ('contact', models.CharField(max_length=300, verbose_name='Телефон')),
                ('address', models.CharField(max_length=300, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('product', models.ManyToManyField(related_name='orders', to='webapp.product')),
            ],
        ),
    ]
