# Generated by Django 4.1.6 on 2023-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default=1, max_length=300, verbose_name='Имя'),
        ),
    ]
